In [4]:
import os
import datetime as dt
import pandas as pd
import sys

sys.path.append("../") # adding path to library

from library.ftx.markets import Markets

In [7]:
m = Markets(os.getenv('FTX_API'), os.getenv('FTX_API_SECRET'))
all_markets = pd.DataFrame(m.get_markets()['result'])
all_markets.head()

,name,enabled,postOnly,priceIncrement,sizeIncrement,minProvideSize,last,bid,ask,price,...,quoteCurrency,underlying,restricted,highLeverageFeeExempt,change1h,change24h,changeBod,quoteVolume24h,volumeUsd24h,tokenizedEquity
0,1INCH-PERP,True,False,0.0001,1.00,1.00,3.1896,3.1852,3.1884,3.1884,...,None,1INCH,False,False,-0.003158,0.010266,0.014251,7.510265e+06,7.510265e+06,NaN
1,1INCH-1231,True,False,0.0001,1.00,1.00,3.3096,3.2675,3.2871,3.2871,...,None,1INCH,False,False,0.001279,0.017710,0.017962,1.292373e+04,1.292373e+04,NaN
2,1INCH/USD,True,False,0.0001,1.00,1.00,3.1873,3.1836,3.1859,3.1859,...,USD,None,False,True,-0.002442,0.009410,0.013585,7.963520e+05,7.963520e+05,NaN
3,AAPL-1231,True,False,0.0100,0.01,0.01,143.3400,142.6900,143.7700,143.3400,...,None,AAPL,True,False,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,True
4,AAPL/USD,True,False,0.0100,0.01,0.01,142.3200,142.3200,143.0600,142.3200,...,USD,None,True,True,0.000000,-0.008085,-0.008085,2.119141e+03,2.119141e+03,True

### Downloading historical data

In [ ]:
start_date = dt.datetime(2020, 1, 1)
end_date = dt.datetime(2021, 8, 1)
resolution = 300  # 5 minutes candles 
market = 'ABNB/USD'
all_data = pd.DataFrame()

while start_date < dt.datetime(2021, 2, 1):
    result = m.get_historical_prices(market, resolution, start_date, start_date + dt.timedelta(days=6))
    start_date += dt.timedelta(days=6)
    all_data = all_data.append(pd.DataFrame(result['result']))

In [72]:
all_data.to_csv('data/ABNBUSD.csv', index=None)

In [53]:
all_data

,startTime,time,open,high,low,close,volume
0,2020-03-28T14:40:00+00:00,1.585406e+12,6240.75,6241.00,6223.50,6224.25,0.0000
1,2020-03-28T14:45:00+00:00,1.585407e+12,6224.25,6234.25,6223.25,6229.25,0.0000
2,2020-03-28T14:50:00+00:00,1.585407e+12,6229.25,6237.25,6229.25,6235.50,0.0000
3,2020-03-28T14:55:00+00:00,1.585407e+12,6235.50,6243.75,6235.25,6239.00,0.0000
4,2020-03-28T15:00:00+00:00,1.585408e+12,6239.00,6245.25,6237.25,6241.50,0.0000
...,...,...,...,...,...,...,...
1496,2021-02-05T20:40:00+00:00,1.612558e+12,37658.00,37760.00,37658.00,37732.00,55109.3303
1497,2021-02-05T20:45:00+00:00,1.612558e+12,37732.00,37759.00,37693.00,37716.00,31070.0687
1498,2021-02-05T20:50:00+00:00,1.612558e+12,37716.00,37753.00,37712.00,37729.00,12809.3527
1499,2021-02-05T20:55:00+00:00,1.612558e+12,37729.00,37794.00,37721.00,37748.00,17656.8924
1500,2021-02-05T21:00:00+00:00,1.612559e+12,37748.00,37753.00,37676.00,37723.00,71892.3390